###
POST http://localhost:3000/library/students/register
Content-Type: application/json

{   
    "name": "Fulaninho de Tal",
    "cpf": "123.456.789-10",
    "address": "R. X, 123, Bairro, Cidade/UF"  
}

###
GET http://localhost:3000/library/students/list

###
GET http://localhost:3000/library/students/search/123.456.789-10

###
POST http://localhost:3000/library/students/edit/123.456.789-10

{   
    "name": "Silva",
    "cpf": "123.456.789-10",
    "address": "R. Y, 456, Bairro, Cidade/UF"  
}

###
DELETE  http://localhost:3000/library/students/delete/0124

###
POST http://localhost:3000/library/books/register
Content-Type: application/json

{
    "cod": "11",
    "title": "Sapiens",
    "status": "AVAILABLE"
}

###
GET http://localhost:3000/library/books/list

###
GET http://localhost:3000/library/books/search/002

###
PUT  http://localhost:3000/library/books/edit/11

{   
    "cod": "10",
    "title": "Sapiens",
    "status": "UNVAILABLE"  
}

###
DELETE  http://localhost:3000/library/books/delete/11


###
POST http://localhost:3000/library/lending/register
Content-Type: application/json

{   
    "studantName": "Fulaninho",
    "studentCpf": "777",
    "booksTitles": "Sapiens",
    "booksCod": "002"   
}